services:
  cairo:
    build: .
    environment:
      - RUN_SCRIPT=${RUN_SCRIPT:-test}
    env_file:
      - ./.env
    ports:
      - "8100:8100"
    volumes:
      # Code directories
      - ./src:/code/src
      - ./libs:/code/libs
      # Builds
      - ./build:/code/build
      # Logs and config
      - ./logs:/code/logs
      - ./.starknet_accounts:/root/.starknet_accounts
      # Scripts
      - ./scripts.sh:/code/scripts.sh
      - ./run.sh:/code/run.sh
    command: sh -c "chmod -R +x ./scripts.sh ./run.sh && ./run.sh"
volumes:
  logvolume01: {}
