export default [
  {
    LocalObservationDateTime: "2022-09-10T01:53:00+09:00",
    EpochTime: 1662742380,
    WeatherText: "Mostly cloudy",
    WeatherIcon: 38,
    HasPrecipitation: false,
    PrecipitationType: null,
    IsDayTime: false,
    Temperature: { Metric: [Object], Imperial: [Object] },
    RealFeelTemperature: { Metric: [Object], Imperial: [Object] },
    RealFeelTemperatureShade: { Metric: [Object], Imperial: [Object] },
    RelativeHumidity: 86,
    IndoorRelativeHumidity: 86,
    DewPoint: { Metric: [Object], Imperial: [Object] },
    Wind: { Direction: [Object], Speed: [Object] },
    WindGust: { Speed: [Object] },
    UVIndex: 0,
    UVIndexText: "Low",
    Visibility: { Metric: [Object], Imperial: [Object] },
    ObstructionsToVisibility: "",
    CloudCover: 76,
    Ceiling: { Metric: [Object], Imperial: [Object] },
    Pressure: { Metric: [Object], Imperial: [Object] },
    PressureTendency: { LocalizedText: "Steady", Code: "S" },
    Past24HourTemperatureDeparture: {
      Metric: [Object],
      Imperial: [Object],
    },
    ApparentTemperature: { Metric: [Object], Imperial: [Object] },
    WindChillTemperature: { Metric: [Object], Imperial: [Object] },
    WetBulbTemperature: { Metric: [Object], Imperial: [Object] },
    Precip1hr: { Metric: [Object], Imperial: [Object] },
    PrecipitationSummary: {
      Precipitation: [Object],
      PastHour: [Object],
      Past3Hours: [Object],
      Past6Hours: [Object],
      Past9Hours: [Object],
      Past12Hours: [Object],
      Past18Hours: [Object],
      Past24Hours: [Object],
    },
    TemperatureSummary: {
      Past6HourRange: [Object],
      Past12HourRange: [Object],
      Past24HourRange: [Object],
    },
    MobileLink:
      "http://www.accuweather.com/en/jp/tokyo/226396/current-weather/226396?lang=en-us",
    Link: "http://www.accuweather.com/en/jp/tokyo/226396/current-weather/226396?lang=en-us",
  },
];
